# Site settings
author: Theodore Schafer
title: Theodore Schafer's Blog
header-img: img/home-bg.png
email: theodore.schafer@gmail.com
copyright_name: Theodore Schafer
description: > # this means to ignore newlines until "baseurl:"
  learning to develop software
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  TheodoreSchafer

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
